# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ""
  os: "linux"
  repository: "yuandrk/kbot"
  tag: "v1.0.1-649f933"
  arch: amd64

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
